### ISSUE TITLE
cmake integration with binary package

### ISSUE THREAD

**Issue by anassmeskini** [intel/tbb#201]
I am using tbb in my cmake project, where I build a library and an executable that links to the library.

My CMakeLists.txt looks like this

```
cmake_minimum_required (VERSION 3.12)

add_library(mylib lib.cpp)
add_executable(exe main.cpp)

find_package(TBB)

target_include_directories(mylib "include")
target_include_directories(exe "include")

target_link_libraries(mylib TBB::tbb)
target_link_libraries(exe mylib)
```

The library compiles fine, but the executable complains about not finding tbb headers, which made look for variables set by the tbb cmake script to set its include directories but I couldn't find them.
When I link TBB::tbb to the executable it compiles fine.

**Comment by AlexVeprev** [comment]
@anassmeskini do you have a simple reproducer (including source code files)? I wasn't able to reproduce it as is with CMake 3.15. I see the similar error only if I add `PRIVATE` keyword before `TBB::tbb`:
```cmake
target_link_libraries(mylib PRIVATE TBB::tbb)
```

BTW I also added `PRIVATE` keywords to `target_include_directories` to address the error:
```
CMake Error at CMakeLists.txt:8 (target_include_directories):
  target_include_directories called with invalid arguments
```

**Comment by anassmeskini** [comment]
@AlexVeprev Here is a simple code to reproduce it.

The project had the following structure
```
project  
│
└───include
│     | lib.h
│   
└───lib.cpp
└───main.cpp
└───CMakeLists.txt
```

include/lib.h
```
#include <tbb/mutex.h>

struct S {
   void foo();

   tbb::mutex mtx;
}
```

lib.cpp
```
#include "lib.h"
#include <iostream>

void S::foo() {
   mtx.lock();
   std::cout << "foo";
   mtx.unlock();
}

```

main.cpp
```
#include "lib.h"

int main(int, char**) {
   S s;
   s.foo();

   return 0;
}

```

CMakeLists.txt
```
cmake_minimum_required (VERSION 3.12)

add_library(lib STATIC "lib.cpp")
add_executable(exe "main.cpp")

target_include_directories(lib  PRIVATE "include") 
target_include_directories(exe  PRIVATE "include") 

find_package(TBB)

target_link_libraries(lib PRIVATE TBB::tbb)
target_link_libraries(exe PRIVATE lib)
```

Here the library compiles with no problems, but for the executable I get an error
```
include/lib.h:1:10: fatal error: tbb/mutex.h: No such file or directory
 #include <tbb/mutex.h>
          ^~~~~~~~~~~~~
``` 

If I add TBB::tbb to the target_link_libraries, the executable compiles fine.

cmake version: 3.13.4

**Comment by AlexVeprev** [comment]
@anassmeskini, from your CMakeLists.txt:
```cmake
target_link_libraries(lib PRIVATE TBB::tbb)
```

From [target_link_libraries documentation](https://cmake.org/cmake/help/latest/command/target_link_libraries.html#libraries-for-a-target-and-or-its-dependents):

> Libraries and targets following **PRIVATE** are linked to, but are not made part of the link interface.

Please do not be confused by the phrase "link interface", actually it affects compilation too. In other words it means that targets following `PRIVATE` are not passed to dependents, so your dependent `exe` target doesn't see `TBB::tbb` target and can't retrieve `TBB::tbb` properties, that's why CMake doesn't insert TBB include path during the compilation of `exe`. But it is required since main.cpp includes lib.h which includes tbb/mutex.h.

Try to replace `PRIVATE` with `PUBLIC` keyword in `target_link_libraries(lib PRIVATE TBB::tbb)`. It should resolve the error.
> Libraries and targets following **PUBLIC** are linked to, and are made part of the link interface.

You can run `make VERBOSE=1` for build to check actual compiler/linker options.
